name: Main
on:
  pull_request:
  push:

jobs:
  test:
    name: Test `show_sls`
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        cache: pip
    - name: Setup dependencies
      run: pip install -r requirements.txt
    - name: Run test
      shell: python
      run: |
        import salt.client
        import salt.config
        import salt.output

        __opts__ = salt.config.minion_config('.salt/etc/minion')
        caller = salt.client.Caller(mopts=__opts__)
        states = caller.cmd("cp.list_states")
        salt.output.display_output(caller.cmd("state.show_sls", states), "yaml", __opts__)
